name = "luccas-portfolio-backend"
main = "worker-fixed.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "luccas-portfolio-backend"

# Note: DROPBOX_ACCESS_TOKEN should be set via Cloudflare dashboard, not here