name = "luccas-portfolio-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "luccas-portfolio-backend"

# Note: DROPBOX_ACCESS_TOKEN should be set via Cloudflare dashboard, not here